# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import torch
torch.empty(2,2)

torch.empty(3,3)

torch.empty(2,2,2)

torch.zeros(2,2,2)

torch.ones(2,2,2)

torch.rand(2,2,2)

torch.manual_seed(100)
torch.rand(2,2,2)

x=torch.tensor([[1,2,3],[12,33,44]])
print(x)

print(x.shape)

torch.empty_like(x)

torch.ones_like(x)